# Generated by Django 5.0.7 on 2024-07-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                default="test@test.com",
                help_text="Email of the customers",
                max_length=255,
                verbose_name="Email",
            ),
            preserve_default=False,
        ),
    ]
