# Generated by Django 5.0.7 on 2024-07-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="received",
            field=models.BooleanField(default=False, verbose_name="Received"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("On hold", "On hold"),
                    ("Pending", "Pending"),
                    ("Ready", "Ready"),
                    ("Collected", "Collected"),
                ],
                default="On hold",
                help_text="Status of the order",
                max_length=255,
                verbose_name="Order Status",
            ),
        ),
    ]
