# Generated by Django 5.0.7 on 2024-07-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Unit Price",
            ),
        ),
    ]
