# Generated by Django 5.0.7 on 2024-07-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                default="abc", max_length=255, verbose_name="Product number"
            ),
            preserve_default=False,
        ),
    ]
